List quotes = [
  '“All our dreams can come true, if we have the courage to pursue them.” – Walt Disney',
  '“The secret of getting ahead is getting started.” – Mark Twain',
  '“Don’t limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve.” – Mary Kay Ash',
  '“The best time to plant a tree was 20 years ago. The second best time is now.” – Chinese Proverb',
  '“Only the paranoid survive.” – Andy Grove',
  '“It’s hard to beat a person who never gives up.” – Babe Ruth',
  '“I wake up every morning and think to myself, ‘how far can I push this company in the next 24 hours.’” – Leah Busque',
  '“If people are doubting how far you can go, go so far that you can’t hear them anymore.” – Michele Ruiz',
  '“We need to accept that we won’t always make the right decisions, that we’ll screw up royally sometimes – understanding that failure is not the opposite of success, it’s part of success.” – Arianna Huffington',
  '“Write it. Shoot it. Publish it. Crochet it, sauté it, whatever. MAKE.” – Joss Whedon',
  '“You’ve gotta dance like there’s nobody watching, love like you’ll never be hurt, sing like there’s nobody listening, and live like it’s heaven on earth.” ― William W. Purkey',
  '“Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.”― Neil Gaiman',
  '“Everything you can imagine is real.”― Pablo Picasso',
  '“When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.” ― Helen Keller',
  '“Do one thing every day that scares you.”― Eleanor Roosevelt',
  '“It’s no use going back to yesterday, because I was a different person then.”― Lewis Carroll',
  '“Smart people learn from everything and everyone, average people from their experiences, stupid people already have all the answers.” – Socrates',
  '“Do what you feel in your heart to be right – for you’ll be criticized anyway.”― Eleanor Roosevelt',
  '“Happiness is not something ready made. It comes from your own actions.” ― Dalai Lama XIV',
  '“Whatever you are, be a good one.” ― Abraham Lincoln',
];

List loadingWeather = [
  'Please wait while the minions do their work',
  'Grabbing extra minions',
  'Doing the heavy lifting',
  'I am working very Hard .... Really',
  'Waking up the minions',
  'You are number 2843684714 in the queue',
  'Please wait while we serve other customers...',
  'Our premium plan is faster',
  "Swapping time and space...",
  "Spinning violently around the y-axis...",
  "Tokenizing real life...",
  "Bending the spoon...",
  "Filtering morale...",
  "We need a new fuse...",
  "Have a good day.",
  "Upgrading Windows, your PC will restart several times. Sit back and relax.",
  "The architects are still drafting",
  "The bits are breeding",
  "We're building the buildings as fast as we can",
  "(Pay no attention to the man behind the curtain)",
  "...and enjoy the elevator music...",
];
List weatherjoke = [
  'What does a cloud wear under his raincoat? Thunderwear!',
  'What did the tornado say to the sports car? Want to go for a spin?',
  'What did one volcano say to the other volcano? I lava you.',
  'What falls but never hits the ground? The temperature.',
  'Why did the man only wear one boot into town? He heard there would be a 50% chance of snow!',
  'What happens when it rains cats and dogs? You might step in a poodle!',
  'What’s a tornado’s favourite game? Twister!',
  'How does the rain tie its shoes? With a rainbow.',
  'What goes up when the rain comes down? An umbrella!',
  'Why shouldn’t you start a fight with a cloud? He’ll storm out on you.',
  'What did one lightning bolt say to the other lightning bolt? You\'re shocking!',
  'What did the hurricane say to the other hurricane? I have my eye on you.',
  'What do you call a grizzly bear caught in the rain? A drizzly bear!',
  'What happens when winter arrives? Autumn leaves!',
  'Why is Britain the wettest country? Because royalty has reigned here for years.',
  'How does a thunderstorm catch fish? With a lightning rod!',
  'When does it rain money? When there\'s a change in the weather.',
  'What\'s a king\'s favourite weather? Hail!',
  'Coming up with weather-related puns is a breeze.',
  'The hottest day of the week is Sun-day.',
  'Lightning storms can be very striking.',
  'I tried to catch some fog, but I mist.',
  'Winter puns are snow joke!',
  'You don\'t like my puns? How cold!',
  'Rain doesn\'t fall...it raindrops!',
  'Local weather reports say there won\'t be any rain for a year, but I drought it.',
  'Did you hear of the story of the tornado? There\'s a twist at the end!',
  'When it rains chickens and ducks, you could say it\'s fowl weather.',
  'It was so cold, one man fell out of bed and broke his pyjamas!',
  'The weather forecast was for freezing cold hail, and sure enough, it was an ice day.',
  'It was a terrible summer for Humpty Dumpty, but he certainly had a great fall.',
  'It was so cold outside that hitchhikers were holding up pictures of thumbs!',
  'It only rains twice a year in London: August through April and May through July.',
];
